accounts/urls.py
from django.conf.urls import url
from . import views, api

urlpatterns = [
    url(r'^signup/$', views.signup_step_1_confirm_email, name="signup_step_1_confirm_email"),
    url(r'^await-confirmation/', views.signup_step_2_await_confirmation),
    url(r'^purchase-ithaca-dollars/', views.purchase_ithaca_dollars),
    url(r'^create_account/(?P<email_key>\w+)', views.signup_step_3_select_account_type, name="select_account_type"),
    url(r'^api/confirm_email/(?P<email_key>\w+)', api.confirm_email, name="api_confirm_email"),
    url(r'^account-information/', views.signup_step_4_account_information),
    url(r'^review/$', views.review),
    url(r'^api/register_account/$', api.register_account, name="api_register_account")
]

pages/urls.py
from django.conf.urls import url
from . import views, api

urlpatterns = [
    url(r'^page-creator/$', views.page_creator),
    url(r'^page-creator/files/$', views.files),
    url(r'^api/add-to-mailing-list/$', api.add_to_mailing_list),
]

staff/urls.py
from django.conf.urls import url
from . import views, api

urlpatterns = [
    url(r'^$', views.staff_front),
    url(r'^login/', views.login_staff),
    url(r'^signup/', views.signup),
    url(r'^dashboard/', views.dashboard),
    url(r'^api/search-users/', api.search_users),
    url(r'^api/confirm-staff/(?P<confirmation_key>\w+)', api.confirm_staff)
]

accounts/models.py
from datetime import datetime
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import UserManager
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.db import models
import uuid
from encrypted_fields.fields import EncryptedCharField
import mandrill
from phonenumber_field.modelfields import PhoneNumberField
from ithacash.sayings import USERNAME_DESCRIPTION, DOMAIN, EMAIL_CONFIMATION_SUBJECT_LINE, VERIFICATION_SUBJECT_LINE
from django.template import Context, loader
from django.conf import settings
from django.core import validators
from django.utils import timezone
import logging

logger = logging.getLogger(__name__)


class IthacashUser(AbstractBaseUser):
    username = models.CharField(max_length=120, unique=True, null=True, default=None, help_text=USERNAME_DESCRIPTION, validators=[validators.MinLengthValidator(5), validators.RegexValidator(r'^[0-9a-zA-Z]*$', 'Only letters and numbers are allowed')])
    full_name = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'username'

    objects = UserManager()


class Email(models.Model):
    address = models.EmailField(unique=True)
    owner = models.ForeignKey(IthacashUser, related_name="emails", blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    confirmed = models.DateTimeField(blank=True, null=True)
    most_recent_confirmation_key = models.CharField(max_length=255)
    wants_to_receive_updates = models.BooleanField(default=False)

    def __unicode__(self):
        return "%s - %s" % (self.address, self.confirmed or "unconfirmed")

    def save(self, *args, **kwargs):
        if not self.most_recent_confirmation_key:
            self.generate_new_confirmation_key()

        return super(Email, self).save(*args, **kwargs)

    def validate_unique(self, exclude=None):
        try:
            super(Email, self).validate_unique(exclude)
        except ValidationError as e:
            try:
                if e.args[0].keys() == ['address'] and e.args[0]['address'][0].args[1] == 'unique':
                    return
                else:
                    raise
            except:
                raise

    def generate_new_confirmation_key(self):
        self.most_recent_confirmation_key = uuid.uuid4().hex

    def confirmation_url(self):
        return reverse("api_confirm_email", kwargs={'email_key': self.most_recent_confirmation_key})

    def send_confirmation_message(self):
        t = loader.get_template('emails/phase_one.txt')
        c = {
            'confirmation_url': "https://%s%s" % (DOMAIN, self.confirmation_url()),
            'form_url': "https://%s%s" % (DOMAIN, reverse("signup_step_1_confirm_email")),
            'email_address': self.address,
        }
        message = t.render(c)

        mandrill_client = mandrill.Mandrill(settings.MANDRILL_API_KEY)

        logger.info("Sending confirmation email to %s" % self.address, self)
        mandrill_client.messages.send(
            {
                'to': [{'email': self.address}],
                'text': message,
                'from_name': 'Ithacash Support',
                'from_email': 'support@ithacash.com',
                'subject': EMAIL_CONFIMATION_SUBJECT_LINE,
            })

    def confirm(self, key):
        if key == self.most_recent_confirmation_key:
            self.confirmed = timezone.now()
            self.save()
            return True
        else:
            return False


class IthacashAccount(models.Model):

    ACCOUNT_TYPE_CHOICES = (
        ('Individual', 'Individual'),
        ('Freelancer', 'Freelancer'),
        ('Standard Business', 'Standard Business'),
        ('Premier Business', 'Premier Business'),
        ('Nonprofit', 'Nonprofit'),
    )

    BILLING_FREQUENCY_CHOICES = (
        ('Monthly', 'Monthly'),
        ('Semi-Annual', 'Semi-Annual')
    )

    owner = models.ForeignKey(IthacashUser, related_name="accounts")

    account_type = models.CharField(max_length=20, choices=ACCOUNT_TYPE_CHOICES)
    entity_name = models.CharField(max_length=255, blank=True)

    billing_frequency = models.CharField(max_length=11, choices=BILLING_FREQUENCY_CHOICES, default='Monthly')

    address_1 = models.CharField(max_length=255,)
    address_2 = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=255)
    state = models.CharField(max_length=255)
    zip_code = models.CharField(max_length=255)
    tin = EncryptedCharField(max_length=255, blank=True, help_text="This is a secure site. Your Tax ID # will not be seen by anyone internally, distributed, or shared.", validators=[validators.MinLengthValidator(9, "This should be exactly 9 numbers. (It has %(show_value)d)"), validators.MaxLengthValidator(9, "This should be exactly 9 numbers. (It has %(show_value)d)")])
    is_ssn = models.BooleanField(default=True, blank=True, choices=((True, 'SSN'), (False, 'EIN')))
    phone_mobile = PhoneNumberField(max_length=255, blank=True)
    phone_landline = PhoneNumberField(max_length=255)
    website = models.URLField(max_length=255, blank=True)
    txt2pay = models.BooleanField(default=False)
    txt2pay_phone = models.BooleanField(default=False)
    electronic_signature = models.CharField(max_length=255)

    created = models.DateTimeField(auto_now_add=True)
    registration_complete = models.BooleanField(default=False)

    def save(self, *args, **kwargs):

        if self.entity_name == '':
            self.entity_name = self.owner.full_name

        return super(IthacashAccount, self).save(*args, **kwargs)

    def send_awaiting_verification_message(self):

        account_email = self.owner.emails.all()[0].address

        t = loader.get_template('emails/please_wait_while_we_verify.txt')
        c = Context({})
        message = t.render(c)

        mandrill_client = mandrill.Mandrill(settings.MANDRILL_API_KEY)

        logger.info("Sending verification email to %s for account %s" % (account_email, self))
        message = mandrill_client.messages.send(
            {
                'to': [{'email': account_email}],  # Right now, users aren't allowed to have more than one email address.
                'text': message,
                'from_name': 'Ithacash Support',
                'from_email': 'support@ithacash.com',
                'subject': VERIFICATION_SUBJECT_LINE,
            })

accounts/views.py
import json
import sys
from django.http.response import HttpResponse, HttpResponseRedirect, JsonResponse, HttpResponseServerError
from django.template.response import SimpleTemplateResponse
from django.shortcuts import render, get_object_or_404
from hendrix.experience import crosstown_traffic
from django import forms

from accounts.models import Email, IthacashUser, IthacashAccount
from ithacash.sayings import EMAIL_ALREADY_IN_SYSTEM
from accounts.properties import ACCOUNT_PROPERTIES
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from .forms import *
from django.views.decorators.cache import never_cache, cache_control
from django.core.exceptions import ObjectDoesNotExist
from django.template import RequestContext


def getting_an_account(request):
    return render(request, 'getting-an-account.html')


def signup_step_1_confirm_email(request):

    return HttpResponseRedirect('/accounts/signup/temporarily-closed/')

    # form = EmailForm(request.POST or None)
    #
    # if request.method == 'POST':
    #
    #     address = request.POST.get('address')
    #
    #     if form.is_valid():
    #
    #         if Email.objects.filter(address=address).exists():
    #             form.add_error('address', EMAIL_ALREADY_IN_SYSTEM)
    #             return (JsonResponse(form.errors, status=400, reason="BAD REQUEST: Invalid form values"))
    #
    #         else:
    #             return (JsonResponse({'success': True}, status=202, reason="OK: Form values accepted"))
    #
    #     else:
    #         return (JsonResponse(form.errors, status=400, reason="BAD REQUEST: Invalid form values"))
    #
    # else:
    #     return render(request, 'accounts/signup-step-1-confirm-email.html', {'form': form})


def signup_step_2_await_confirmation(request):

    if request.method == 'POST':

        email_object, created = Email.objects.get_or_create(address=request.POST['address'])

        if created:

            @crosstown_traffic()
            def send_email_later():
                email_object.send_confirmation_message()

            return HttpResponseRedirect('/accounts/create_account/{}'.format(email_object.most_recent_confirmation_key))

        else:
            return HttpResponseRedirect('/accounts/signup/')

    else:
        return HttpResponseRedirect('/accounts/signup/')


@cache_control(no_cache=True, must_revalidate=True, no_store=True, max_age=0)
def signup_step_3_select_account_type(request, email_key):

    email_object = get_object_or_404(Email, most_recent_confirmation_key=email_key)

    # Create the user and associated account if newly confirmed
    if email_object.owner is None:
        email_object.owner = IthacashUser.objects.create()
        email_object.save()

    try:
        account = IthacashAccount.objects.get(owner_id=email_object.owner_id)
        account_form = AccountSelectionForm(request.POST or None, instance=account)
    except IthacashAccount.DoesNotExist:
        account_form = AccountSelectionForm(request.POST or None)

    if request.method == 'POST':

        if account_form.is_valid():
            return (JsonResponse({'success': True}, status=202, reason="OK: Form values accepted"))

        else:
            return (JsonResponse(account_form.errors, status=400, reason="BAD REQUEST: Invalid form values"))

    else:
        return render(request, 'accounts/signup-step-3-select-account-type.html', {'form': account_form, 'user_id': email_object.owner_id})


@cache_control(no_cache=True, must_revalidate=True, no_store=True, max_age=0)
def signup_step_4_account_information(request):

    if request.method == 'POST':

        # Submit account type
        if "validate" not in request.POST and 'user_id' in request.POST:
            user_id = request.POST.get('user_id')

            try:
                account = IthacashAccount.objects.get(owner_id=user_id)
                account_selection_form = AccountSelectionForm(request.POST or None, instance=account)
                account_selection_form.save()
                account_form = AccountForm(instance=account)
            except ObjectDoesNotExist:
                account_selection_form = AccountSelectionForm(request.POST or None)
                account_form = AccountForm(initial={'account_type': request.POST.get('account_type')})

            user_form = UserSignupForm(instance=IthacashUser.objects.get(id=user_id))

            context = {
                'account_form': account_form,
                'user_form': user_form,
                'user_id': user_id
            }

            return render(request, 'accounts/signup-step-4-account-information.html', context)

        # Handle Step 4 validation
        else:
            user_id = request.POST.get('user_id')

            user_object = IthacashUser.objects.get(id=user_id)

            try:
                account = IthacashAccount.objects.get(owner_id=user_id)
                account_form = AccountForm(request.POST, instance=account)
            except ObjectDoesNotExist:
                account_form = AccountForm(request.POST)

            user_form = UserSignupForm(request.POST, instance=user_object)

            if account_form.is_valid() and user_form.is_valid():

                return JsonResponse({'success': True}, status=202, reason="OK: Form values accepted")

            else:
                errors = {}
                errors.update(account_form.errors)
                errors.update(user_form.errors)

                return JsonResponse(errors, status=400, reason="BAD REQUEST: Invalid form values")


@cache_control(no_cache=True, must_revalidate=True, no_store=True, max_age=0)
def review(request):

    if request.method == 'POST':

        user_id = request.POST.get('user_id')

        user_object = IthacashUser.objects.get(id=user_id)
        email_object = Email.objects.get(owner=user_object)

        try:
            account_object = IthacashAccount.objects.get(owner=user_object)
            account_form = AccountForm(request.POST, instance=account_object)
        except ObjectDoesNotExist:
            account_form = AccountForm(request.POST)

        user_form = UserSignupForm(request.POST, instance=user_object)

        if account_form.is_valid() and user_form.is_valid():

            try:
                account_object = account_form.save(commit=False)
                account_object.owner = user_object
                account_object.save()
                account_form.save_m2m()
            except:
                account_form.save()

            user_form.save()

            context = {
                'user': user_object,
                'account': account_object,
                'email': email_object,
                'paypal_form': settings.PAYPAL_SETTINGS,
                'paypal_button_id': settings.PAYPAL_SETTINGS['button_ids'][account_object.account_type],
                'sign_up_fee': ACCOUNT_PROPERTIES[account_object.account_type]['SIGN_UP_FEE'],
                'monthly_cost': ACCOUNT_PROPERTIES[account_object.account_type]['MONTHLY'],
                'txt2pay_phone_cost': ACCOUNT_PROPERTIES['TXT2PAY_PHONE']
            }

            return render(request, 'accounts/signup-step-5-review.html', context)

        else:
            return HttpResponseServerError()

    else:
        return HttpResponse("Please click the back button to return to the previous page or click the link in your confirmation email and try again.")


def whoops(request):
    return render(request, 'whoops.html')


def purchase_ithaca_dollars(request):
    return render(request, 'purchase-ithaca-dollars.html')

accounts/templates/accounts/signup-step-4-account-information.html
{% extends 'subpage.html' %}
{% load staticfiles %}

{% block styles %}
<style>

    #headline {
        margin-bottom: 5px;
    }

    h2 {
        font-size: 2em;
    }

    #account-type {
        font-size: 1.2em;
        margin: 15px 0;
    }

    h3 {
        margin-bottom: 10px;
    }

    h3 + p {
        margin-top: 0;
    }

    #sign-up-pathway {
        width: 100%;
        background-color: rgb(140, 170, 69);
        color: white;
        padding: 10px 0;
        margin-bottom: 30px;
    }

    #sign-up-pathway ul {
        margin: 0;
        padding: 0;
        text-transform: uppercase;
        font-size: 1em;
        line-height: 1em;
    }

    #sign-up-pathway ul li {
        display: inline;
        margin: 0 10px;
        list-style-type: none;
    }

    #sign-up-pathway ul li::before {
        height: 25px;
        width: 25px;
        display: inline-block;
        background-color: #B3D377;
        border-radius: 50%;
        content: "•";
        color: white;
        text-align: center;
        vertical-align: middle;
        line-height: 25px;
    }

    #sign-up-pathway ul li.selected::before {
        background-color: rgb(77, 116, 23);
    }


    #sign-up-pathway ul li.completed::before {
        background-color: rgb(77, 116, 23);
        content: "✔";
        font-size: .9em;
    }

    input, select {
        margin-top: 10px;
        margin-bottom: 0;
        width: 350px;
    }

    input[type=checkbox] {
        width: auto;
    }

    article {
        width: 100%;
    }

    sidebar {
        display: none;
    }

    body {
        padding-bottom: 60px;
    }

    #id_is_ssn {
        text-align: center;
        padding: 0;
        margin: 0;
        width: 350px;
        font-size: 1.4em;
        display: inline-block;
    }

    #id_is_ssn li {
        display: inline;
        margin: 0 10px;
    }

    #id_is_ssn li::before {
        content: none;
        margin: 0;
    }

    #id_is_ssn input {
        width: auto;
        margin: 0;
        vertical-align: middle;
    }

    #account-signature h3 {
        margin-top: 40px;
    }
</style>
{% endblock %}

{% block heading %}Get an Account{% endblock %}

{% block subheadline %}
<div id="sign-up-pathway">
<div class="container">
    <ul>
        <li class="completed">Confirm</li>
        <li class="completed">Select</li>
        <li class="selected">Account Info</li>
        <li>Review</li>
    </ul>
</div>
</div>
{% endblock %}

{% block article %}

    <section>
    <div class="white-background">
        <h2><b>Step 3:</b> Account Information</h2>
        <p><strong>It&rsquo;s free</strong>, but it&rsquo;s still your money, so we need your real information to make your account payment as safe as possible.</p>

        <form id="account" method="POST" action="/accounts/review/" class="clear">
            {% csrf_token %}
            <input type="hidden" value="True" name="validate">
            <input type="hidden" value="{{ user_id }}" name="user_id">
            <div style="width: 45%; float: left;">
                <div id="username" class="field">
                    {% if user_form.username.errors %}
                        {% for error in user_form.username.errors %}
                            <p>{{ user_form.username }} <span class="error-message">{{ error|escape }}</span></p>
                        {% endfor %}
                    {% else %}
                        <p>{{ user_form.username }} {% if user_form.username.help_text %}<span class="helptext-wrapper"><span class="helptext">{{ user_form.username.help_text }}</span></span>{% endif %}</p>
                    {% endif %}
                </div>
                <div id="account-type" class="field">
                    <input type="hidden" name="account_type" id="id_account_type" value="{{ account_form.account_type.value }}">
                    <p><b>Account type:</b> {{ account_form.account_type.value }}</p>
                </div>
                <div id="full-name" class="field">
                    {% if user_form.full_name.errors %}
                        {% for error in user_form.full_name.errors %}
                            <p>{{ user_form.full_name }} <span class="error-message">{{ error|escape }}</span></p>
                        {% endfor %}
                    {% else %}
                        <p>{{ user_form.full_name }} {% if user_form.full_name.help_text %}<span class="helptext-wrapper"><span class="helptext">{{ user_form.full_name.help_text }}</span></span>{% endif %}</p>
                    {% endif %}
                </div>
                {% if account_form.account_type.value != 'Individual' %}
                <div id="entity-name" class="field">
                    {% if account_form.entity_name.errors %}
                        {% for error in account_form.entity_name.errors %}
                            <p>{{ account_form.entity_name }} <span class="error-message">{{ error|escape }}</span></p>
                        {% endfor %}
                    {% else %}
                        <p>{{ account_form.entity_name }} {% if account_form.entity_name.help_text %}<span class="helptext-wrapper"><span class="helptext">{{ account_form.entity_name.help_text }}</span></span>{% endif %}</p>
                    {% endif %}
                </div>
                {% endif %}
                <div id="account-address-1" class="field">
                    {% if account_form.address_1.errors %}
                        {% for error in account_form.address_1.errors %}
                            <p>{{ account_form.address_1 }} <span class="error-message">{{ error|escape }}</span></p>
                        {% endfor %}
                    {% else %}
                        <p>{{ account_form.address_1 }} {% if account_form.address_1.help_text %}<span class="helptext-wrapper"><span class="helptext">{{ account_form.address_1.help_text }}</span></span>{% endif %}</p>
                    {% endif %}
                </div>
                <div id="account-address-2" class="field">
                    {% if account_form.address_2.errors %}
                        {% for error in account_form.address_2.errors %}
                            <p>{{ account_form.address_2 }} <span class="error-message">{{ error|escape }}</span></p>
                        {% endfor %}
                    {% else %}
                        <p>{{ account_form.address_2 }} {% if account_form.address_2.help_text %}<span class="helptext-wrapper"><span class="helptext">{{ account_form.address_2.help_text }}</span></span>{% endif %}</p>
                    {% endif %}
                </div>
                <div id="account-city" class="field">
                    {% if account_form.city.errors %}
                        {% for error in account_form.city.errors %}
                            <p>{{ account_form.city }} <span class="error-message">{{ error|escape }}</span></p>
                        {% endfor %}
                    {% else %}
                        <p>{{ account_form.city }} {% if account_form.city.help_text %}<span class="helptext-wrapper"><span class="helptext">{{ account_form.city.help_text }}</span></span>{% endif %}</p>
                    {% endif %}
                </div>
                <div id="account-state" class="field">
                    {% if account_form.state.errors %}
                        {% for error in account_form.state.errors %}
                            <p>{{ account_form.state }} <span class="error-message">{{ error|escape }}</span></p>
                        {% endfor %}
                    {% else %}
                        <p>{{ account_form.state }} {% if account_form.state.help_text %}<span class="helptext-wrapper"><span class="helptext">{{ account_form.state.help_text }}</span></span>{% endif %}</p>
                    {% endif %}
                </div>
                <div id="account-zip" class="field">
                    {% if account_form.zip_code.errors %}
                        {% for error in account_form.zip_code.errors %}
                            <p>{{ account_form.zip_code }} <span class="error-message">{{ error|escape }}</span></p>
                        {% endfor %}
                    {% else %}
                        <p>{{ account_form.zip_code }} {% if account_form.zip_code.help_text %}<span class="helptext-wrapper"><span class="helptext">{{ account_form.zip_code.help_text }}</span></span>{% endif %}</p>
                    {% endif %}
                </div>
            </div>
            <div style="width: 45%; float: right;">
            <div id="account-landline" class="field">
                {% if account_form.phone_landline.errors %}
                    {% for error in account_form.phone_landline.errors %}
                        <p>{{ account_form.phone_landline }} <span class="error-message">{{ error|escape }}</span></p>
                    {% endfor %}
                {% else %}
                    <p>{{ account_form.phone_landline }} {% if account_form.phone_landline.help_text %}<span class="helptext-wrapper"><span class="helptext">{{ account_form.phone_landline.help_text }}</span></span>{% endif %}</p>
                {% endif %}
            </div>
            <div id="account-txt2pay" class="field">
                {% if account_form.txt2pay.errors %}
                    {% for error in account_form.txt2pay.errors %}
                        <p><label>{{ account_form.txt2pay }} I&rsquo;d like to use TXT2PAY</label> <span class="error-message">{{ error|escape }}</span></p>
                    {% endfor %}
                {% else %}
                    <p><label>{{ account_form.txt2pay }} I&rsquo;d like to use TXT2PAY</label> {% if account_form.txt2pay.help_text %}<span class="helptext-wrapper"><span class="helptext">{{ account_form.txt2pay.help_text }}</span></span>{% endif %}</p>
                {% endif %}
            </div>
            <div id="account-txt2pay-phone" class="field">
                {% if account_form.txt2pay_phone.errors %}
                    {% for error in account_form.txt2pay_phone.errors %}
                        <p><label>{{ account_form.txt2pay_phone }} I&rsquo;d like to lease a TXT2PAY phone for $10/month</label> <span class="error-message">{{ error|escape }}</span></p>
                    {% endfor %}
                {% else %}
                    <p><label>{{ account_form.txt2pay_phone }} I&rsquo;d like to lease a TXT2PAY phone for $10/month</label> {% if account_form.txt2pay_phone.help_text %}<span class="helptext-wrapper"><span class="helptext">{{ account_form.txt2pay_phone.help_text }}</span></span>{% endif %}</p>
                {% endif %}
            </div>
            <div id="account-mobile" class="field">
                {% if account_form.phone_mobile.errors %}
                    {% for error in account_form.phone_mobile.errors %}
                        <p>{{ account_form.phone_mobile }}<span class="error-message">{{ error|escape }}</span></p>
                    {% endfor %}
                {% else %}
                    <p>{{ account_form.phone_mobile }}{% if account_form.phone_mobile.help_text %}<span class="helptext-wrapper"><span class="helptext">{{ account_form.phone_mobile.help_text }}</span></span>{% endif %}</p>
                {% endif %}
            </div>
            {% if account_form.account_type.value != 'Individual' %}
            <h3>Tax Information</h3>
            <div id="account-tin" class="field">
                {% if account_form.tin.errors %}
                    {% for error in account_form.tin.errors %}
                        <p>{{ account_form.tin }} <span class="error-message">{{ error|escape }}</span></p>
                    {% endfor %}
                {% else %}
                    <p>{{ account_form.tin }} {% if account_form.tin.help_text %}<span class="helptext-wrapper"><span class="helptext">{{ account_form.tin.help_text }}</span></span>{% endif %}</p>
                {% endif %}
            </div>
            <div id="account-is-ssn" class="field">
                {% if account_form.is_ssn.errors %}
                    {% for error in account_form.is_ssn.errors %}
                        <p>{{ account_form.is_ssn }} <span class="error-message">{{ error|escape }}</span></p>
                    {% endfor %}
                {% else %}
                    <p>{{ account_form.is_ssn }} {% if account_form.is_ssn.help_text %}<span class="helptext-wrapper"><span class="helptext">{{ account_form.is_ssn.help_text }}</span></span>{% endif %}</p>
                {% endif %}
            </div>
            {% endif %}
            <div id="account-signature" class="field">
                <h3>Signature</h3>
                {% if account_form.electronic_signature.errors %}
                    {% for error in account_form.electronic_signature.errors %}
                        <p>{{ account_form.electronic_signature }} <span class="error-message">{{ error|escape }}</span></p>
                    {% endfor %}
                {% else %}
                    <p>{{ account_form.electronic_signature }} {% if account_form.electronic_signature.help_text %}<span class="helptext-wrapper"><span class="helptext">{{ account_form.electronic_signature.help_text }}</span></span>{% endif %}</p>
                {% endif %}
            </div>

                <p><button name="user_id" value="{{ user_id }}">Next</button></p>
            </div>
        </form>


    </div>
    </section>
{% endblock article %}

{% block sidebar %}{% endblock %}


{% block scripts %}
<script src="{% static 'accounts/js/accounts.js' %}"></script>
{% endblock %}