pages/urls.py
from django.conf.urls import url
from . import views, api

urlpatterns = [
    url(r'^page-creator/$', views.page_creator),
    url(r'^page-creator/files/$', views.files),
    url(r'^api/add-to-mailing-list/$', api.add_to_mailing_list),
]

staff/urls.py
from django.conf.urls import url
from . import views, api

urlpatterns = [
    url(r'^$', views.staff_front),
    url(r'^login/', views.login_staff),
    url(r'^signup/', views.signup),
    url(r'^dashboard/', views.dashboard),
    url(r'^api/search-users/', api.search_users),
    url(r'^api/confirm-staff/(?P<confirmation_key>\w+)', api.confirm_staff)
]

pages/forms.py
from django import forms
from django.contrib.flatpages.forms import FlatpageForm
from pages.models import *
from django.contrib.flatpages.models import FlatPage


class add_to_mailing_list_form(forms.Form):

    auto_id = False

    email_address = forms.EmailField(max_length=255)
    mailing_list_id = forms.HiddenInput()


class send_message_form(forms.Form):

    message_from = forms.EmailField(max_length=255, label='', widget=forms.TextInput(attrs={'placeholder': 'Email'}))

    message = forms.CharField(max_length=255, label='', widget=forms.Textarea(attrs={'placeholder': 'Name'}))


class FlatPageForm(FlatpageForm):

    url = forms.CharField(help_text="e.g. /how-it-works/general-info/earning-spending/", label="", widget=forms.TextInput(attrs={'placeholder': 'Page URL'}))
    title = forms.CharField(help_text="e.g. Earning &amp; Spending", label="", widget=forms.TextInput(attrs={'placeholder': 'Page Title'}))
    content = forms.CharField(help_text="Please follow the <a href='/style-guide/' target='_blank'>Ithacash Web Style Guide</a>", label="", widget=forms.Textarea(attrs={'placeholder': 'Page Content'}))

    # Default values
    enable_comments = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'hide'}), required=False)
    registration_required = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'hide'}), required=False)
    sites = forms.ChoiceField(widget=forms.Select(attrs={'class': 'hide'}), choices=(('1', 'ithacash.com'),), initial='1')
    template_name = forms.CharField(help_text="The template that this page will be based on (defaults to flatpages/template.html)", widget=forms.TextInput(), initial="flatpages/template.html")


class SubPageForm(forms.ModelForm):

    class Meta:
        model = SubPage
        fields = {'heading', 'meta_desc', 'meta_keywords', 'meta_image'}

    heading = forms.CharField(help_text="e.g. Earning &amp; Spending", label="", widget=forms.TextInput(attrs={'placeholder': 'Page Heading'}))
    meta_desc = forms.CharField(help_text="Succinct Ithacash description", initial="Ithacash", label="", widget=forms.Textarea(attrs={'placeholder': 'Meta Description'}))
    meta_keywords = forms.CharField(help_text="e.g. ithaca, currency, local", initial="ithaca, local, currency", label="", widget=forms.TextInput(attrs={'placeholder': 'Meta Keywords'}))
    meta_image = forms.CharField(initial="https://ithacash.com/static/img/ithacash_logo_rgb_325x124.png", label="", widget=forms.TextInput(attrs={'placeholder': 'Meta Image'}))


class FileUploadForm(forms.ModelForm):

    class Meta:
        model = UploadedFiles
        fields = {'file'}

    file = forms.FileField(
        label='Select a file',
        help_text='Images to be shown on pages should be below 50kb. Full-size images should be available via a link only'
    )
    # title = forms.CharField(label="", widget=forms.TextInput(attrs={'placeholder': 'Image Title'}))

pages/templates/pages/files.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/page-creator.css' %}">
<style>
    img {
        max-width: 300px;
    }

    input[name="file"] {
        border: 1px solid #8caa45;
        padding: 5px;
    }

    .image {
        display: inline-block;
        width: 33%;
        text-align: center;
        float: none;
    }
</style>
{% endblock %}

{% block header %}
<h1>Image Upload</h1>
{% endblock %}

{% block content %}
<div class="container">
<form method="POST" action="" class="standard-form" enctype="multipart/form-data">
    {% csrf_token %}

<p>{{ upload_form.file }} <span class="helptext-wrapper dark-gray-background"><span class="helptext">{{ upload_form.file.help_text|safe }}</span></span></p>
<p>{{ upload_form.title }}</p>

<button>Upload</button>
</form>

{% for file in files %}
    <div class="image">
        <p><img src="{{ file.file.url }}"><br>{{ file.title }}</p>
    </div>
{% endfor %}
{% endblock %}

pages/templates/pages/page-creator.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/page-creator.css' %}">
<style>
    #content {
        padding-top: 0;
    }

    section {
        padding: 0;
    }

    button {
        font-size: 1em;
        padding: 5px 10px;
    }

    .left button {
        font-size: .9em;
    }

    .del {
        background-color: rgb(255, 94, 94);
    }

    table {
        border-collapse: collapse;
        width: 100%;
    }

    th {
        text-align: left;
    }

    tbody tr {
        border-top: 1px solid #555;
        border-bottom: 1px solid #555;
    }

    td, th {
        padding: 10px;
    }

    .url {
        word-break: break-all;
    }

    #mceu_9 {
        width: calc(100% - 45px);
        display: inline-block;
    }

    textarea {
        color: black;
        width: calc(100% - 45px);
    }

    #id_content {
        height: 15em;
    }

    #id_meta_desc {
        height: 4.8em;
    }

    #id_meta_keywords, #id_meta_image {
        width: calc(100% - 45px);
    }

    .action {
        width: 45px;
    }
</style>
{% endblock %}

{% block header %}
<h1>Ithacash Subpages</h1>
{% endblock %}

{% block content %}
<section>
<div class="container">
    <div class="left">
    <table>
        <thead>
            <tr>
                <th class="title">Title</th>
                <th class="url">URL</th>
                <th class="heading">Heading</th>
                <th class="action"></th>
            </tr>
        </thead>
        <tbody>
        {% for page in pages %}
            <tr>
                <td>{{ page.title }}</td>
                <td class="url"><a href="{{ page.url }}" target="_blank">{{ page.url }}</a></td>
                <td>{{ page.subpage.heading }}</td>
                <td><button name="page_id" value="{{ page.id }}" class="edit">Edit</button> <!-- <button name="page_id" value="{{ page.id }}" class="del">Delete</button> --></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>

    <div class="right">
        <form method="POST" action="" class="standard-form" enctype="multipart/form-data">
            {% csrf_token %}
                <div class="hide">
                    {{ flatpage_form.enable_comments }} {{ flatpage_form.registration_required }} {{ flatpage_form.sites }}
                </div>

                <p>{{ flatpage_form.url }} <span class="helptext-wrapper dark-gray-background"><span class="helptext">{{ flatpage_form.url.help_text|safe }}</span></span></p>

                <p>{{ subpage_form.heading }} <span class="helptext-wrapper dark-gray-background"><span class="helptext">{{ subpage_form.heading.help_text|safe }}</span></span></p>

                <p>{{ flatpage_form.title }} <span class="helptext-wrapper dark-gray-background"><span class="helptext">{{ flatpage_form.title.help_text|safe }}</span></span></p>

                <p>{{ flatpage_form.template_name }} <span class="helptext-wrapper dark-gray-background"><span class="helptext">{{ flatpage_form.template_name.help_text|safe }}</span></span></p>

                <p><a href="files/" class="green-button" target="_blank">Upload Images</a></p>

                <p>{{ flatpage_form.content }} <span class="helptext-wrapper dark-gray-background"><span class="helptext">{{ flatpage_form.content.help_text|safe }}</span></span></p>

                <h3>SEO Metadata</h3>

                <p>{{ subpage_form.meta_desc }} <span class="helptext-wrapper dark-gray-background"><span class="helptext">{{ subpage_form.meta_desc.help_text|safe }}</span></span></p>

                <p>{{ subpage_form.meta_keywords }} <span class="helptext-wrapper dark-gray-background"><span class="helptext">{{ subpage_form.meta_keywords.help_text|safe }}</span></span></p>

                <p>{{ subpage_form.meta_image }} <span class="helptext-wrapper dark-gray-background"><span class="helptext">{{ subpage_form.meta_image.help_text|safe }}</span></span></p>

                <p><button name="id" value="{{ flatpage_form.initial.id|default_if_none:"" }}">Update</button></p>
            </div>
        </form>
    </div>
</div>
</section>
{% endblock %}

{% block scripts %}
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script>

    // TinyMCE
    tinymce.init({
        plugins: "link, fullscreen, image, imagetools, textcolor, code, template",
        selector: "#id_content",
        convert_urls: false,
        toolbar: "undo redo | styleselect | bold italic link forecolor | bullist | blockquote | removeformat image | template | code | fullscreen",
        content_css: "{% static 'css/page-creator.css' %}",
        elementpath: false,
        menubar: false,
        statusbar: false,
        browser_spellcheck: true,
        invalid_elements: "script",
        style_formats: [
            {title: "Headers", items: [
                {title: "Header 3", format: "h3"},
                {title: "Header 4", format: "h4"}
            ]},
            {title: "Blocks", items: [
                {title: "Standout", format: "blockquote"}
            ]},
            {title: "Inline", items: [
                {title: "Bold", icon: "bold", inline: "b"},
                {title: "Italic", icon: "italic", format: "italic"},
                {title: "Underline", icon: "underline", format: "underline"},
                {title: "Highlight", inline: "mark"},
                {title: "Superscript", icon: "superscript", format: "superscript"},
                {title: "Subscript", icon: "subscript", format: "subscript"}
            ]}
        ],
        link_class_list: [
            {title: 'None', value: ''},
            {title: "> CTA link", inline: "a", value: "cta-link"},
            {title: "Angled CTA →", value: "angled-cta-right light-green-background"},
            {title: "← Angled CTA", value: "angled-cta-left dark-green-background"},
            {title: "Button", value: "green-button"}
        ],
        image_list: "/pages/page-creator/files/?json",
        imagetools_toolbar: 'imageoptions',
        textcolor_map: [
            "4d7416", "Dark green",
            "8caa45", "Light green",
            "dd1800", "Red",
            "777777", "Bold gray"
        ],
        templates: [
            {title: "Email signup form", description: "A form with an email input field and a hidden mailing list id field. Please use the code button (<>) in the toolbar to add the MailChimp mailing list id to the hidden field.", url: "{% static 'pages/tinymce-templates/email-signup-form.html' %}"}
        ]
    });

    $('.left button').click(function() {
        page_id = $(this).val();
        action = $(this).text() == 'Edit' ? 'edit' : 'del'

        $.ajax({
            type: "POST",
            url: "",
            data: {id:parseInt(page_id), action:action, csrfmiddlewaretoken: "{{ csrf_token }}"}
        })
        .success(function( response ) {

            if ( typeof response.flatpage != 'undefined') {
                flatpage = response.flatpage;
                subpage = response.subpage;

                $('#id_url').val(flatpage.url);
                $('#id_title').val(flatpage.title);
                tinyMCE.activeEditor.setContent(flatpage.content);
                $('#id_subpage select').val(subpage.flatpage);
                $('#id_heading').val(subpage.heading);
                $('#id_meta_desc').val(subpage.meta_desc);
                $('#id_meta_keywords').val(subpage.meta_keywords);
                $('.right button').val(flatpage.id);
            }

            else {
                page_id = response.page_id;

                tr = $('.left button[value=' + page_id + ']').parents('tr').remove();
            }
        });
    })

    $.fn.extend({
    insertAtCaret: function(myValue){
      return this.each(function(i) {
        if (document.selection) {
          //For browsers like Internet Explorer
          this.focus();
          var sel = document.selection.createRange();
          sel.text = myValue;
          this.focus();
        }
        else if (this.selectionStart || this.selectionStart == '0') {
          //For browsers like Firefox and Webkit based
          var startPos = this.selectionStart;
          var endPos = this.selectionEnd;
          var scrollTop = this.scrollTop;
          this.value = this.value.substring(0, startPos)+myValue+this.value.substring(endPos,this.value.length);
          this.focus();
          this.selectionStart = startPos + myValue.length;
          this.selectionEnd = startPos + myValue.length;
          this.scrollTop = scrollTop;
        } else {
          this.value += myValue;
          this.focus();
        }
      });
    }
    });

    $('.styling-element').click(function() {
        $('#id_content').insertAtCaret($('span', this).html());
    });
</script>
{% endblock %}